-- ACTIVITAT 1
-- NATURAL JOIN
SELECT
    CITY,
    DEPARTMENT_NAME,
    POSTAL_CODE,
    DEPARTMENT_ID
FROM
    DEPARTMENTS
    NATURAL JOIN LOCATIONS
WHERE
    (DEPARTMENT_ID = 10
    OR DEPARTMENT_ID = 20
    OR DEPARTMENT_ID = 30)
    AND CITY = 'Seattle';

-- USING
SELECT
    CITY,
    DEPARTMENT_NAME,
    POSTAL_CODE,
    DEPARTMENT_ID
FROM
    DEPARTMENTS
    JOIN LOCATIONS USING(LOCATION_ID)
WHERE
    (DEPARTMENT_ID = 10
    OR DEPARTMENT_ID = 20
    OR DEPARTMENT_ID = 30)
    AND CITY = 'Seattle';
    
-- ON
SELECT
    CITY,
    DEPARTMENT_NAME,
    POSTAL_CODE,
    DEPARTMENT_ID
FROM
    DEPARTMENTS
    JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
WHERE
    (DEPARTMENT_ID = 10
    OR DEPARTMENT_ID = 20
    OR DEPARTMENT_ID = 30)
    AND CITY = 'Seattle';
    
-- CLASSIC
SELECT
    CITY,
    DEPARTMENT_NAME,
    POSTAL_CODE,
    DEPARTMENT_ID
FROM
    DEPARTMENTS,
    LOCATIONS
WHERE
    DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
    AND (DEPARTMENT_ID = 10
    OR DEPARTMENT_ID = 20
    OR DEPARTMENT_ID = 30)
    AND CITY = 'Seattle';



-- ACTIVITAT 2
-- SQL99
SELECT
    FIRST_NAME,
    LAST_NAME,
    DEPARTMENT_NAME
FROM
    EMPLOYEES
    LEFT JOIN DEPARTMENTS
    ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

-- CLASSIC
SELECT
    FIRST_NAME,
    LAST_NAME,
    DEPARTMENT_NAME
FROM
    EMPLOYEES,
    DEPARTMENTS
WHERE
    EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID(+);



-- ACTIVITAT 3
SELECT
    e.LAST_NAME,
    cap.LAST_NAME
FROM
    EMPLOYEES e
    JOIN EMPLOYEES cap ON e.MANAGER_ID = cap.EMPLOYEE_ID;



-- ACTIVITAT 4
WITH ORG_CHART (EMPLOYEE_ID, LAST_NAME, MANAGER_ID, LVL) AS (
    SELECT
        E.EMPLOYEE_ID,
        E.LAST_NAME,
        E.MANAGER_ID,
        0 AS LVL

    FROM
        EMPLOYEES E
    WHERE
        E.MANAGER_ID IS NULL UNION ALL
        (SELECT
            E.EMPLOYEE_ID,
            E.LAST_NAME,
            E.MANAGER_ID,
            OC.LVL + 1
        FROM
            EMPLOYEES E
            JOIN ORG_CHART OC
            ON E.MANAGER_ID = OC.EMPLOYEE_ID)
)
SELECT
    RPAD('-',
    LVL * 2,
    '-') || LAST_NAME AS EMPLOYEE_NAME
FROM
    ORG_CHART
ORDER BY EMPLOYEE_ID, MANAGER_ID ASC;
