-- ACTIVITAT 1
-- NATURAL JOIN
SELECT
    CITY,
    DEPARTMENT_NAME,
    POSTAL_CODE,
    DEPARTMENT_ID
FROM
    DEPARTMENTS
    NATURAL JOIN LOCATIONS
WHERE
    (DEPARTMENT_ID = 10
    OR DEPARTMENT_ID = 20
    OR DEPARTMENT_ID = 30)
    AND CITY = 'Seattle';

-- USING
SELECT
    CITY,
    DEPARTMENT_NAME,
    POSTAL_CODE,
    DEPARTMENT_ID
FROM
    DEPARTMENTS
    JOIN LOCATIONS USING(LOCATION_ID)
WHERE
    (DEPARTMENT_ID = 10
    OR DEPARTMENT_ID = 20
    OR DEPARTMENT_ID = 30)
    AND CITY = 'Seattle';
    
-- ON
SELECT
    CITY,
    DEPARTMENT_NAME,
    POSTAL_CODE,
    DEPARTMENT_ID
FROM
    DEPARTMENTS
    JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
WHERE
    (DEPARTMENT_ID = 10
    OR DEPARTMENT_ID = 20
    OR DEPARTMENT_ID = 30)
    AND CITY = 'Seattle';
    
-- CLASSIC
SELECT
    CITY,
    DEPARTMENT_NAME,
    POSTAL_CODE,
    DEPARTMENT_ID
FROM
    DEPARTMENTS,
    LOCATIONS
WHERE
    DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
    AND (DEPARTMENT_ID = 10
    OR DEPARTMENT_ID = 20
    OR DEPARTMENT_ID = 30)
    AND CITY = 'Seattle';



-- ACTIVITAT 2
-- SQL99
SELECT
    FIRST_NAME,
    LAST_NAME,
    DEPARTMENT_NAME
FROM
    EMPLOYEES
    LEFT JOIN DEPARTMENTS
    ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

-- CLASSIC
SELECT
    FIRST_NAME,
    LAST_NAME,
    DEPARTMENT_NAME
FROM
    EMPLOYEES,
    DEPARTMENTS
WHERE
    EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID(+);
    